site:
  about:
    siteName: Arg2P
    siteDescription: Argumentation tuProlog
theme:
  primaryColor: '#7E80CF'
  metaComponents:
    - type: 'orchidSearch'
    - type: mermaid
      selector: '.mermaid' # optional
  legacySearch: false
  menu:
    - type: link
      title: Home
      url: /
    - type: 'wiki'
assets:
  sourceDirs:
    - 'assets/media'
services:
  compilers:
    binaryExtensions:
      - 'png'
#wiki:
#  defaultConfig:
#    createPdf: true
wiki:
  theme:
    key: 'Editorial'
    primaryColor: '#7E80CF'