name: Test
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-jvm:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        java-version: [17]
        jdk-dist:
          - adopt-hotspot
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ matrix.java-version }}-${{ matrix.jdk-dist }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22
      - uses: DanySK/build-check-deploy-gradle-action@3.7.14
        with:
          java-distribution: ${{ matrix.jdk-dist }}
          java-version: ${{ matrix.java-version }}
          build-command: |
            ./gradlew jsMainClasses jsTestClasses --parallel || ./gradlew jsMainClasses jsTestClasses --parallel
          check-command: |
            ./gradlew jvmTest --parallel --continue || ./gradlew jvmTest --parallel --continue
          should-run-codecov: false

  test-js:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        node-version:
          - '20.18.1'
    runs-on: ${{ matrix.os }}
    env:
      ORG_GRADLE_PROJECT_nodeVersion: ${{ matrix.node-version }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ matrix.node-version }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22
      - uses: DanySK/build-check-deploy-gradle-action@3.7.14
        with:
          build-command: |
            ./gradlew jsMainClasses jsTestClasses --parallel || ./gradlew jsMainClasses jsTestClasses --parallel
          check-command: |
            ./gradlew jsTest --parallel --continue || ./gradlew jsTest --parallel --continue
          clean-command: ./gradlew cleanTest
          should-run-codecov: false
